### PR TITLE
Text formating

### PR DESCRIPTION
**Pull request by h3nr1ke**
## Purpose of this pull request

format for terminal or configuration texts missing in the operating system and php areas

## Affected pages

https://experienceleague.adobe.com/docs/commerce-operations/performance-best-practices/software.html

### CODE REVIEW

**Review by jeff-matthews — COMMENTED** [review]
Thanks for the contribution @h3nr1ke!

I agree that the code block is the way to go for both examples. But maybe both should be "text" since the code blocks are for config files. I'm not sure if "conf" is an accepted lexer, so "text" is a safe bet.

**Comment by jeff-matthews** [comment]
Also, please sign the Adobe CLA so we can continue processing this PR. Just click the link next to the **Adobe CLA Signed?** check at the bottom of this PR.

Screen Shot 2022-05-02 at 9 56 00 AM

**Comment by dobooth** [comment]
Fixed in the internal repo.

**Comment by jeff-matthews** [comment]
@h3nr1ke, please sign the Adobe CLA so that we can finish processing your PR. We cannot merge until that check clears.

**Comment by jeff-matthews** [comment]
Actually, I didn't see my previous comment in May to sign the CLA until just now. Closing as abandoned.

**Pull request closed without merging**
