### PR TITLE
Clarify the logic for detecting maintenance mode.

### PR DESCRIPTION
**Pull request by paulpartington-cti**
## Purpose of this pull request

This pull request attempts to clarify the logic which explains how and when maintenance mode is enabled.

## Affected pages

https://experienceleague.adobe.com/en/docs/commerce-operations/installation-guide/tutorials/maintenance-mode

### CODE REVIEW

**Review by jeff-matthews — APPROVED** [review]

**Comment by jeff-matthews** [comment]
@devops-devdocs import the pr

**Comment by devops-devdocs** [comment]
Something went wrong

**Comment by jeff-matthews** [comment]
@devops-devdocs import the pr

**Comment by devops-devdocs** [comment]
Something went wrong

**Comment by dshevtsov** [comment]
@devops-devdocs import the pr

**Comment by devops-devdocs** [comment]
@devops-devdocs imported this pull request

**Pull request merged**
