### PR TITLE
Update product-availability.md to add Catalog Service details

### PR DESCRIPTION
**Pull request by sgonzalezmangana**
Adding the CS within the list of services and compatible/supported versions.  The CS must also be added to the "Compatibility" table. @dobooth what is the difference between compatible and supported?

## Purpose of this pull request

This pull request (PR) ...

## Affected pages

- ...

## Links to Magento Open Source code

- ...

### CODE REVIEW

**Comment by dobooth** [comment]
Ported to internal repo.

**Comment by jeff-matthews** [comment]
@AdobeDocs/commerce-writers, just a friendly reminder not to close external PRs and recreate them internally. The proper process is to push the contributor's branch to the internal repo, create a PR there, then merge. The repo sync will change the status of the external PR to "merged" and this will not only preserve reliable repo stats, but it will also improve the contributor experience.

**Comment by barnato-v** [comment]
Hi @Jeff ***@***.***>

Can we have a meeting to discuss?

I think there is some confusion on my end. I met with @Bob ***@***.***> and documented in the following wiki<https://wiki.corp.adobe.com/pages/viewpage.action?pageId=2727125022>:

Assess the PR in the public repo. Copying PRs from the public repo to the enterprise/internal<https://git.corp.adobe.com/AdobeDocs/commerce-operations.en> repo can be complex and there can be errors. Consider making the change yourself in your local copy of the enterprise /internal repo<https://git.corp.adobe.com/AdobeDocs/commerce-operations.en>, in GitHub desktop, if the change proposed by the external contributor is small. For example, removing typos, or minor wording changes. If you decide the change is small and you will make the change yourself in your local copy of the enterprise /internal repo<https://git.corp.adobe.com/AdobeDocs/commerce-operations.en>, in GitHub desktop, it is still best practice to leave a comment in the PR, saying something like "Thanks. We updated the help documentation". Then click Close with comment. The contributor will get a notification.

     However, if the change is significant and provided by a subject matter expert you should copy the PR from the public repo<https://github.com/AdobeDocs/commerce-operations.en> into  the enterprise repo<https://git.corp.adobe.com/AdobeDocs/commerce-operations.en>, once you have had a technical and writer review. Once you decide the PR is ready to be copied from the public repo to the internal repo go to the target repo. Pull origin to make sure your local clone is in sync with the main branch.
It sounds like the above is not the right way to process PRs in the external repo?

Victoria Barnato  |  Senior Technical Writer, Customer Engineering  |  Adobe  |  C 512 915 1611 |  ***@***.******@***.***>


From: Jeff Matthews ***@***.***>
Date: Thursday, November 17, 2022 at 10:02 AM
To: AdobeDocs/commerce-operations.en ***@***.***>
Cc: Victoria Barnato ***@***.***>, Team mention ***@***.***>
Subject: Re: [AdobeDocs/commerce-operations.en] Update product-availability.md to add Catalog Service details (PR #41)

EXTERNAL: Use caution when clicking on links or opening attachments.



@AdobeDocs/commerce-writers<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Forgs%2FAdobeDocs%2Fteams%2Fcommerce-writers&data=05%7C01%7Cbarnato%40adobe.com%7Cbfb105f199244e0955e108dac8b51ec3%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C638042977506001782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3V3aZCagSi1sJsHQGJgEPIIPchpSO46kWxyZ9Ok%2BQzo%3D&reserved=0>, just a friendly reminder not to close external PRs and recreate them internally. The proper process is to push the contributor's branch to the internal repo, create a PR there, then merge. The repo sync will change the status of the external PR to "merged" and this will not only preserve reliable repo stats, but it will also improve the contributor experience.

**Comment by barnato-v** [comment]
Hi Victoria,

I’m happy to meet to discuss.

Maybe it would help if I clarified that my comment was meant to target writers who use the commerce-operations.en repo. The preferred process for managing external PRs in that repo is to push the contributor’s branch (and original commit SHA) instead of re-create the changes under a new commit SHA and closing the PR.

While the method you documented in the wiki may be acceptable for other ExL repos, it is not acceptable for the commerce-operations.en repo.


Jeff Matthews  |  Sr. Manager, Technical Writing – Adobe Commerce  |  Adobe  | ***@***.******@***.***>

From: Victoria Barnato ***@***.***>
Date: Thursday, November 17, 2022 at 11:24 AM
To: AdobeDocs/commerce-operations.en ***@***.***>, AdobeDocs/commerce-operations.en ***@***.***>, Jeff Matthews ***@***.***>, Bob Bringhurst ***@***.***>
Cc: Team mention ***@***.***>
Subject: Re: [AdobeDocs/commerce-operations.en] Update product-availability.md to add Catalog Service details (PR #41)
Hi @Jeff ***@***.***>

Can we have a meeting to discuss?

I think there is some confusion on my end. I met with @Bob ***@***.***> and documented in the following wiki<https://wiki.corp.adobe.com/pages/viewpage.action?pageId=2727125022>:

Assess the PR in the public repo. Copying PRs from the public repo to the enterprise/internal<https://git.corp.adobe.com/AdobeDocs/commerce-operations.en> repo can be complex and there can be errors. Consider making the change yourself in your local copy of the enterprise /internal repo<https://git.corp.adobe.com/AdobeDocs/commerce-operations.en>, in GitHub desktop, if the change proposed by the external contributor is small. For example, removing typos, or minor wording changes. If you decide the change is small and you will make the change yourself in your local copy of the enterprise /internal repo<https://git.corp.adobe.com/AdobeDocs/commerce-operations.en>, in GitHub desktop, it is still best practice to leave a comment in the PR, saying something like "Thanks. We updated the help documentation". Then click Close with comment. The contributor will get a notification.

     However, if the change is significant and provided by a subject matter expert you should copy the PR from the public repo<https://github.com/AdobeDocs/commerce-operations.en> into  the enterprise repo<https://git.corp.adobe.com/AdobeDocs/commerce-operations.en>, once you have had a technical and writer review. Once you decide the PR is ready to be copied from the public repo to the internal repo go to the target repo. Pull origin to make sure your local clone is in sync with the main branch.
It sounds like the above is not the right way to process PRs in the external repo?

Victoria Barnato  |  Senior Technical Writer, Customer Engineering  |  Adobe  |  C 512 915 1611 |  ***@***.******@***.***>


From: Jeff Matthews ***@***.***>
Date: Thursday, November 17, 2022 at 10:02 AM
To: AdobeDocs/commerce-operations.en ***@***.***>
Cc: Victoria Barnato ***@***.***>, Team mention ***@***.***>
Subject: Re: [AdobeDocs/commerce-operations.en] Update product-availability.md to add Catalog Service details (PR #41)

EXTERNAL: Use caution when clicking on links or opening attachments.



@AdobeDocs/commerce-writers<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Forgs%2FAdobeDocs%2Fteams%2Fcommerce-writers&data=05%7C01%7Cbarnato%40adobe.com%7Cbfb105f199244e0955e108dac8b51ec3%7Cfa7b1b5a7b34438794aed2c178decee1%7C0%7C0%7C638042977506001782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3V3aZCagSi1sJsHQGJgEPIIPchpSO46kWxyZ9Ok%2BQzo%3D&reserved=0>, just a friendly reminder not to close external PRs and recreate them internally. The proper process is to push the contributor's branch to the internal repo, create a PR there, then merge. The repo sync will change the status of the external PR to "merged" and this will not only preserve reliable repo stats, but it will also improve the contributor experience.

**Pull request closed without merging**
