### PR TITLE
Fix wrong example for custom patch

### PR DESCRIPTION
**Pull request by ihor-sviziev**
## Purpose of this pull request

This pull request (PR) fixes incorrect link to commit and the patch content

## Affected pages

- https://experienceleague.adobe.com/docs/commerce-operations/upgrade-guide/patches/overview.html#custom-patches

## Links to Magento Open Source code

- ...

### CODE REVIEW

**Review by jeff-matthews — APPROVED** [review]

**Comment by jeff-matthews** [comment]
Thanks @ihor-sviziev! You're our first contributor🏅

**Comment by dobooth** [comment]
PR #1!

**Comment by jeff-matthews** [comment]
HI @ihor-sviziev, I merged a copy of your branch with our internal delivery repo (https://github.com/AdobeDocs/commerce-operations.en/commit/38b054bbae8ba116557ce367c8397c646c837558). 

But since I used a squash commit, the repo sync is unable to "merge" your original PR. I'll update the repo settings to prevent that in the future. Thanks for your contribution.

**Comment by jeff-matthews** [comment]
Ordinarily, when we merge a copy of a contributors branch with the private mainline delivery repo, the original PR will appear to be merged after the repo synchronization service pushes the changes to the public repo. The only exception to that is if we use a squash commit. Don't worry, it won't happen again. Future PRs will merge as expected if approved.

**Pull request closed without merging**
