### PR TITLE
Use Short Array Notation in env.php Example

### PR DESCRIPTION
**Pull request by pykettk**
## Purpose of this pull request

This pull request (PR) replaces the `array()` notation used in the example `env.php` snippet with the short `[]` notation to ease readability and reflect how the file will _actually_ look to users.

## Affected pages

- https://experienceleague.adobe.com/en/docs/commerce-operations/configuration-guide/cache/redis/redis-session

### CODE REVIEW

**Review by jeff-matthews — APPROVED** [review]

**Comment by jeff-matthews** [comment]
@devops-devdocs import the pr

**Comment by jeff-matthews** [comment]
Thanks for the PR @pykettk. Please sign the Adobe CLA in the checks section so we can merge this.

**Comment by devops-devdocs** [comment]
@devops-devdocs imported this pull request

**Comment by pykettk** [comment]
@jeff-matthews It looks like it's already signed? Or is it a different CLA to the one used for the `magento/magento2` repo?

image

**Comment by jeff-matthews** [comment]
Ah! Thanks @pykettk. I guess I was mistaken or there was a delay in the check showing success.

**Comment by pykettk** [comment]
It's all good - thanks for such a prompt response, @jeff-matthews 💪

**Pull request merged**
