### PR TITLE
Fixed typos and formatting

### PR DESCRIPTION
**Pull request by asrar7787**
## Purpose of this pull request

Fixed typos and formatting

## Affected pages

- https://experienceleague.adobe.com/docs/commerce-operations/implementation-playbook/architecture/integration-strategy.html?lang=en

## Links to Magento Open Source code

- N/A

### CODE REVIEW

**Review by jeff-matthews — APPROVED** [review]
Thanks for the contribution @asrar7787!

**Comment by jeff-matthews** [comment]
Looks like you need to sign the Adobe CLA before we can merge @asrar7787. Please click the link for the failed check.

**Comment by jeff-matthews** [comment]
@asrar7787, please sign the Adobe CLA so that we can merge your contribution.

**Comment by asrar7787** [comment]
@jeff-matthews signed and done from my side

**Pull request merged**
